### ISSUE TITLE
Save Subgraphs

### ISSUE THREAD

**Issue by gundramleifert** [gundramleifert/exp_tf#1]
save subgraphs (e.g. neural network) out train-Graph and re-use them in another training

**Comment by TobiasGruening** [comment]
Maybe have a look at 
https://blog.metaflow.fr/tensorflow-saving-restoring-and-mixing-multiple-models-c4c94d5d7125#.jlfyxaezp

??

**Comment by gundramleifert** [comment]
to getd dict for specific prefix:
def get_op(prefix):
    dict = {}
    if prefix[-1] != '/':
        prefix = prefix + '/'
    res = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope=prefix)
    for t in res:
        key = t.name
        key = key[len(prefix):]
        dict[str(key)] = t
        print(dict)
    return dict
